# Generated by Django 4.1.5 on 2023-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skooba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='rest',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
    ]
