# Generated by Django 4.1.5 on 2023-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skooba', '0002_workout_reps_workout_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.CharField(max_length=50),
        ),
    ]
