# Generated by Django 4.1.5 on 2023-03-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skooba', '0003_workout_sets_alter_workout_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
    ]
