# Generated by Django 4.1.5 on 2023-03-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skooba', '0005_workoutexercise_workout_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='sets',
        ),
    ]
