# Generated by Django 4.1.7 on 2023-04-17 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skooba', '0006_remove_workout_reps_remove_workout_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
